/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'to' : Principal,
  'from' : Principal,
  'text' : string,
  'timestamp' : Time,
}
export interface Job {
  'id' : bigint,
  'status' : JobStatus,
  'completedAt' : [] | [Time],
  'title' : string,
  'ownerPrincipal' : Principal,
  'createdAt' : Time,
  'assignedWorker' : [] | [Principal],
  'description' : string,
  'workersNeeded' : bigint,
  'amount' : bigint,
  'payType' : PayType,
  'location' : string,
}
export interface JobApplication {
  'appliedAt' : Time,
  'jobId' : bigint,
  'worker' : Principal,
}
export type JobStatus = { 'assigned' : null } |
  { 'open' : null } |
  { 'completed' : null };
export type PayType = { 'hourly' : null } |
  { 'daily' : null };
export interface Payout {
  'status' : PayoutStatus,
  'jobId' : bigint,
  'worker' : Principal,
  'amount' : bigint,
}
export type PayoutStatus = { 'paid' : null } |
  { 'unpaid' : null };
export type Time = bigint;
export interface UserProfile {
  'ratingSum' : bigint,
  'principal' : Principal,
  'displayName' : string,
  'ratingCount' : bigint,
  'role' : UserRole,
  'phoneNumber' : string,
}
export type UserRole = { 'owner' : null } |
  { 'worker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignWorkerToJob' : ActorMethod<[bigint, Principal], undefined>,
  'completeJob' : ActorMethod<[bigint], undefined>,
  'createJob' : ActorMethod<
    [string, string, PayType, bigint, bigint, string],
    bigint
  >,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getJobApplications' : ActorMethod<[bigint], Array<JobApplication>>,
  'getJobById' : ActorMethod<[bigint], Job>,
  'getOwnerRating' : ActorMethod<[Principal], [] | [number]>,
  'getPayoutsForWorker' : ActorMethod<[Principal], Array<Payout>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPayoutAsPaid' : ActorMethod<[bigint], undefined>,
  'rateOwner' : ActorMethod<[Principal, bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, UserRole, string], undefined>,
  'sendMessage' : ActorMethod<[bigint, Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];