/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PayType = IDL.Variant({ 'hourly' : IDL.Null, 'daily' : IDL.Null });
export const JobStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
});
export const Time = IDL.Int;
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'completedAt' : IDL.Opt(Time),
  'title' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : Time,
  'assignedWorker' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'workersNeeded' : IDL.Nat,
  'amount' : IDL.Nat,
  'payType' : PayType,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'owner' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'ratingSum' : IDL.Nat,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'role' : UserRole,
  'phoneNumber' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'text' : IDL.Text,
  'timestamp' : Time,
});
export const JobApplication = IDL.Record({
  'appliedAt' : Time,
  'jobId' : IDL.Nat,
  'worker' : IDL.Principal,
});
export const PayoutStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const Payout = IDL.Record({
  'status' : PayoutStatus,
  'jobId' : IDL.Nat,
  'worker' : IDL.Principal,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignWorkerToJob' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'completeJob' : IDL.Func([IDL.Nat], [], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Text, PayType, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getJobApplications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobById' : IDL.Func([IDL.Nat], [Job], ['query']),
  'getOwnerRating' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getPayoutsForWorker' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payout)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPayoutAsPaid' : IDL.Func([IDL.Nat], [], []),
  'rateOwner' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, UserRole, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PayType = IDL.Variant({ 'hourly' : IDL.Null, 'daily' : IDL.Null });
  const JobStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'completedAt' : IDL.Opt(Time),
    'title' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : Time,
    'assignedWorker' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'workersNeeded' : IDL.Nat,
    'amount' : IDL.Nat,
    'payType' : PayType,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'owner' : IDL.Null, 'worker' : IDL.Null });
  const UserProfile = IDL.Record({
    'ratingSum' : IDL.Nat,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'role' : UserRole,
    'phoneNumber' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  const JobApplication = IDL.Record({
    'appliedAt' : Time,
    'jobId' : IDL.Nat,
    'worker' : IDL.Principal,
  });
  const PayoutStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const Payout = IDL.Record({
    'status' : PayoutStatus,
    'jobId' : IDL.Nat,
    'worker' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignWorkerToJob' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'completeJob' : IDL.Func([IDL.Nat], [], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, PayType, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getJobApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobById' : IDL.Func([IDL.Nat], [Job], ['query']),
    'getOwnerRating' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getPayoutsForWorker' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payout)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPayoutAsPaid' : IDL.Func([IDL.Nat], [], []),
    'rateOwner' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, UserRole, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };